batch_size: 16
max_node: 8
num_workers: 0
dropout: 0.5
edge_gat_hidden_size: 128
edge_gat_input_size: 64
edge_gat_output_size: 128
gat_n_heads: 4
lambda1: 0.6
lambda2: 0.4
lr: 1e-3
node_gat_hidden_size: 256
node_gat_input_size: 128
node_gat_output_size: 256
rel_emb_nb: 10
stroke_emb_nb: 150
loss_gamma: 2
patience: 20
min_delta: 1e-6
epochs: 100
shuffle: True
node_class_nb: 114
edge_class_nb: 26