batch_size: 8
dropout: 0.4
edge_class_nb: 26
edge_gat_hidden_size: 256
edge_gat_input_size: 64
edge_gat_output_size: 256
epoch: 300
gat_n_heads: 8
lambda1: 0.8
lambda2: 0.19999999999999996
loss_gamma: 2
lr: 0.00036254709753650487
max_node: 6
min_delta: 1.0e-05
node_class_nb: 114
node_gat_hidden_size: 32
node_gat_input_size: 32
node_gat_output_size: 128
num_workers: 0
patience: 30
rel_emb_nb: 10
shuffle: true
stroke_emb_nb: 150
