dropout: 0.5
edge_class_nb: 26
edge_gat_hidden_size: 384
edge_gat_input_size: 64
edge_gat_output_size: 192
edge_input_size: 40
gat_n_heads: 4
lambda1: 0.4
lambda2: 0.6
lr: 0.0001
min_delta: 1.0e-06
node_class_nb: 114
node_gat_hidden_size: 512
node_gat_input_size: 96
node_gat_output_size: 224
node_input_size: 100
patience: 30
